### REGISTER ADMIN
POST http://localhost:3000/api/users/resgister
Accept: application/json

{
    "name": "adminName",
    "surname": "adminSurname",
    "nick": "admin",
    "pasword": "adminadmin",
    "email": "admin@admin.com"
}
###