### REGISTER ADMIN
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "name": "adminName",
    "surname": "adminSurname",
    "nick": "admin",
    "password": "adminadmin",
    "email": "admin@admin.com"
}
###