import Others from "./Texts";

const langEn: Others = {
    activityNamePlaceholder: "Activity name",
    sportActivity: "Select sport",
    activityTeam: "Select home team",
    openActivity: "Open activity",
    activityDay: "Activity day",
    email: "email",
    emailExample: "name.surname@live.u-tad.com",
    password: "password",
    notRegistered: "Not registered?",
    yesRegistered: "Are you registered?",
    dataProtection: "data protection",
    updateChanges: "update changes",
    keepAccount: "Keep sesion",
    title: "U-tad Sports",
    login: "login",
    register: "register",
    activities: "activities",
    createActivity: "create activity",
    tournaments: "tournaments",
    createTeam: "create team",
    teams: "teams",
    events: "upcoming events",
    results: "results",
    start: "start",
    football: "football",
    basketball: "basketball",
    padel: "padel",
    // "INGENIERIA Y CIENCIAS": "science and engineering",
    // ANIMACION: "animation",
    // "DISENO DIGITAL": "digital desing",
    // "GRADO SUPERIOR": "",
    // VIDEOJUEGOS: "videogames",
    START: "starting",
    IN_PROCESS: "in process",
    END: "end",
    PISTA_01: "track 1",
    PISTA_02: "track 2",
    personalInfo: "personal info",
    logOut: "log out",
    myTeams: "my teams",
    myEvents: "my events",
    myHistory: "my history",
    openTeams: "open teams",
    joinTeam: "join team",
    joinTournament: "join tournament",
    news: "news",
    ganadorTorneo: "tournament winner",
    createTournament: "create tournament",
    inscriptionActivity: "join activity",
    test: "test",
    ResultsActivity: "activity results",
    ResultsTorneo: "torunament results",
    ganadorActividad: "activity winner",
    createdBy: "created by",
    teamPlayers: "team players",
    viewTeam: "view team",
    viewActivity: "view activity",
    join: "join",
    captain: "captain",
    description: "description",
    teamName: "team name",
    selectCaptain: "select your captain",
    maxPlayers: "max number of players",
    createNew: "create a new",
    en: "english",
    es: "spanish",
    repeatPassword: "repeat password",
    nick: "nick name",
    name: "name",
    surname: "surname"
}

export default langEn;