import ResultsActivity from "../routes/ResultsActivity";
import Texts from "./Texts";

const langEs: Texts = {
    title: "U-tad Sports",
    login: "iniciar sesion",
    register: "registrarse",
    activities: "actividades",
    createActivity: "crear actividad",
    tournaments: "torneos",
    createTeam: "crear un equipo",
    teams: "equipos",
    events: "prox. eventos",
    results: "resultados",
    start: "inicio",
    football: "fútbol",
    basketball: "baloncesto",
    padel: "pádel",
    // "INGENIERIA Y CIENCIAS": "ingeniería y ciencias",
    // ANIMACION: "animación",
    // "DISENO DIGITAL": "diseño digital",
    // "GRADO SUPERIOR": "grado superior",
    // VIDEOJUEGOS: "videojuegos",
    START: "empezado",
    IN_PROCESS: "en curso",
    END: "terminado",
    PISTA_01: "pista 1",
    PISTA_02: "pista 2",
    personalInfo: "información personal",
    logOut: "cerrar sesión",
    myTeams: "mis equipos",
    myEvents: "mis eventos",
    myHistory: "mi historial",
    openTeams: "equipos abiertos",
    joinTeam: "inscribirse a un equipo",
    joinTournament: "inscribirse a un torneo",
    news: "noticias",
    ganadorTorneo: "ganador del torneo",
    createTournament: "crear torneo",
    inscriptionActivity: "inscripcion Actividad",
    test: "test",
    ResultsActivity: "resultados de las actividades",
    ResultsTorneo: "resultados de los torneos",
    ganadorActividad: "ganador de la actividad",
    createdBy: "creado por",
    teamPlayers: "jugadores del equipo",
    viewTeam: "ver equipo",
    viewActivity: "ver actividad",
    join: "inscribirse",
    captain: "capitan",
    description: "descripción",
    teamName: "nombre del equipo",
    selectCaptain: "selecciona al capitan",
    maxPlayers: "máximo número de jugadores"
};

export default langEs;